myproj/myfileapp/urls.py
from django.urls import path
from . import views


app_name = "fileapp"

urlpatterns = [
    
    path("",views.index),
    path("upload",views.send_files,name="uploads")

]

myproj/myproj/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("myfileapp.urls",namespace="fileapp"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproj/myfileapp/models.py
from django.db import models

# Create your models here.


class myuploadfile(models.Model):
    myfiles = models.FileField(upload_to="")
    info = models.CharField(max_length=255)

    def __str__(self):
        return self.info

myproj/myfileapp/views.py
import pytesseract
from django.shortcuts import render, HttpResponse, redirect
from . models import myuploadfile
from PIL import Image

pytesseract.pytesseract.tesseract_cmd = 'C:/OCR/Tesseract-OCR/tesseract.exe'
# Create your views here.


def index(request):
    context = {
        "data": myuploadfile.objects.all(),
    }
    return render(request, "index.html", context)


def send_files(request):
    if request.method == "POST":
        myfile = request.FILES.getlist("uploadfoles")

        for f in myfile:
            extractedInformation = pytesseract.image_to_string(
                Image.open(f))
            myuploadfile(myfiles=f, info=extractedInformation).save()
            print(extractedInformation)

        return index(request)
        # return HttpResponse("ok")
        # return redirect("fileapp:index")

myproj/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />

    <title>Image Uploader</title>
  </head>
  <body>
    <div class="container">
      <div class="py-5 text-center bg-secondary text-white mb-2">
        <h1 class="mb-4">Upload Images</h1>
        <form
          action="{% url 'fileapp:uploads' %}"
          method="POST"
          enctype="multipart/form-data"
        >
          <input type="file" multiple name="uploadfoles" accept="image/*"/>
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Image Upload</button>
        </form>
      </div>
      <div class="row">
        {% for d in data %}
        <div class="col-sm-4">
          <div class="card m-2">
            <img
              src="{{d.myfiles.url}}"
              alt=""
              class="card-img-top"
              height="250px"
            />
            <div class="card-footer">
              <h4 class="text-muted" contenteditable="true">
                {{d.myfiles.name}}
              </h4>
              <p contenteditable="true">{{d.info}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>